import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Provider } from "react";
import Header from "./components/Headers";
import Footer from "./components/footer/Footer";
import Brands from "./components/footer/Brands";
import Newsletter from "./components/footer/Newsletter";
// import theme from "./theme/Theme";
import { ThemeProvider } from "@emotion/react";
import ThemeRegistry from "./theme/ThemeRegistry";
import CssBaseline from '@mui/material/CssBaseline';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
const playfair = Playfair_Display({ subsets: ['latin'], variable: '--font-playfair' });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      
      className={`${inter.variable} ${playfair.variable}`}>
        {/* <ThemeProvider> */}
        <ThemeRegistry>
        <CssBaseline/>
        <Header/>
        {children}
        <Brands/> 
        <Newsletter/>
        <Footer/>
        </ThemeRegistry>
       

        {/* </ThemeProvider> */}
        
      </body>
    </html>
  );
}
